Web/WebServer.js
It should now display as "Interval: X hour(s) and Y minute(s)"
=> Changed interval display in extension gallery

Commands/Public/about.js
Changed bug/suggestion reporting to link to GAwesomeBot GitHub instead
of AB.
Updated bot title and credits to match the GAB home page.
Changed the AB url to GAB's home page. It didn't make sense leaving the
Discord link as `config.discord_url` unless the home page was also the
self-host URL (but that didn't seem sensible either), so I changed this
to GAB's Discord link as well.
=> Updated about links

Configuration/commands.json
The messages command in AB4 still supports the 'me' suffix, but the command usage does not reflect this.
Likewise, the kick command also supports the optional reason suffix, but the usage does not reflect this.
=> Updated usage for messages and kick commands

Modules/ExtensionStructures/Message.js
When run from an extension, message.mentions now returns an array of Member objects. For some bizarre reason Eris returns the mentions array by user ID in ascending order (totally illogical, in my opinion), so
through cumbersome means I've reordered the array in order of the user mentioned in the message. The snag is that multiple mentions of the _same_ user will be substituted for a single mention (but why would anyone do that?)
Probably not the most elegant solution possible, but it solves the problem of mentions not working, puts mentions in order and passes additional user information about mentioned users, such as AvatarURL, status, etc. to extensions.
=> Fixed user mentions for extensions

Modules/ExtensionStructures/Message.js
Instead of reordering erisMessage.mentions (why did I bother?), it is
more efficient to simply grab the mentions from the message content (as
this was done to determine the order anyway) and pass user IDs through
the Guild object to give us an array of mentioned users' Member objects
in the order that those users were mentioned.
=> Improved message.mentions in extensions.

Commands/Public/shorten.js
Shorten <link> returns a shortened `https://goo.gl` link, which cannot be passed back to the command (to return the full URL) because it only attempts to expand `http://goog.gl` links. Fixed by adding another condition.
=> Fixed shorten command to recognise https://goog.gl links

Extensions/.gitignore
New installs still require manual creation of an empty Extensions
directory, otherwise extensions won't save. I've updated the instance
self-host guide to specify that the directory should be created, but
this is the simpler solution.
=> Added (empty) Extensions directory

Events/ready.js
A better fix is to come on the development branch.
=> Hotfix for bot.endGiveaway.

Commands/PM/profile.js, Commands/Public/weather.js, Database/Schemas/userSchema.js
The default temperature unit for the weather command was Fahrenheit, but
this is uncommon in most of the world (which uses Celsius). Setting to F
or C is problematic because whoever doesn't use the default is forced to
define the temperature unit every time they use the weather command.
For example, if a user wants to see the weather in Paris in Celsius they
must type `weather Paris C`. If that user then sets their profile
location to Paris, they can simply run `weather`. But this convenience
is undermined by the fact that `weather` will show them the weather in
Paris in **Fahrenheit**. So despite setting their profile location, they
must run `weather Paris C` every time.
My initial thought was to simply set the default to C, but this causes
the inverse problem for those using Fahrenheit …
=> Weather unit added to profile

Modules/ExtensionStructures/Member.js
In extensions, there are times when the user object and member object are needed for different purposes. For example, when we want to PM a member from an extension, we need their user object so we can call [userobj].createMessage().
If we have the user object through message.author, this is fine. But beyond author, extensions only retrieve *member* objects. e.g. through guild.members.get(id) or through message.mentions[x]. In these cases, we need the user object (as it contains getDMChannel() from eris, and createMessage() in User.js takes care of the rest).
The eris Member object contains a .user property, so the user object passes with Member. This *should* allow us to be able to get the user object. But in extensions (Member.js), the user
object is passed via a getter, and this means …
=> Always pass full user property via member object

Modules/Trivia.js, Web/WebServer.js
Trivia was previously broken with custom sets. The trivia game would end immediately, as when using a custom set, Trivia.js had not properly defined the custom trivia JSON and did not cater for the fact that once imported to the database, the items exist under an 'items' property.
Additionally, when browsing the Ongoing Activities page of the Admin Console, an error was returned and the page inaccessible. This was due to WebServer.js erroneously passing a non-existent variable (set instead of set_id) from the channel's trivia property.
Custom trivia sets now working, and the ongoing activities page works as intended when trivia games are ongoing.
=> Fixed trivia

Platform/Discord.js
A simple fix to resolve the crash that occurs as a result of 'then' being undefined when bot.muteMember is triggered on a filter, per issue #64.
=> Fixed crash on mute when a filter is triggered

Modules/ExtensionStructures/Member.js
Adding a member to/removing a member from a role is possible within an extension however the method is a little cumbersome. The extension must get the user's current roles array into a variable, then either push to or slice that array before then using the edit method i.e. `message.member.edit({ roles: arrayvar }).`
Eris already has Member.addRole/removeRole functions, and it seems both sensible and convenient to make them available to extensions.
=> Added roleAdd and roleRemove to extension Member API

Modules/ExtensionStructures/Member.js
For the same reason that getters have in some instances caused problems in extensions (such as with mentions), this change is a must. Otherwise, member.permissions can return _the bot's_ permissions object and not the member's. Try creating an extension with `logMsg(JSON.stringify(message.mentions[0].permission))` and mention various users. You'll see it doesn't return correct permissions objects.  After switching from a getter, works perfectly (as expected ;))
=> Always pass member.permission in extensions

Modules/ExtensionStructures/Channel.js
channel.editMessage in Channel.js did not pass the content parameter, so it didn't work. Simple fix. Now works as it should.
=> Fixed channel.editMessage (extensions)

Modules/ExtensionStructures/Invite.js
As has been the problem with numerous other properties, Inviter was a getter. This meant the invite creator's user object wasn't passing with the Invite object and wasn't retrievable (an extension could not even see which user created the invite).
To reproduce: `guild.getInvites(cb => {logMsg(JSON.stringify(cb))});`
Resolved by always passing the User object via .inviter.
=> Fixed Invite.inviter (extensions) as was empty

Modules/ExtensionStructures/Role.js
Role.permissions frequently empty. To reproduce:
```
logMsg(JSON.stringify(guild.roles.get(ROLE ID).permissions));
```
Even for a role with full administrative permissions, the result is:
`{"allow":0,"deny":0,"json":{}}`
As has been the problem with numerous other properties (e.g. Member.permissions in issue #77), the fault lies in the fact that permissions() was a getter. By always passing permissions the problem is avoided and Role permissions are able to be properly read and used.
I've also removed Role.asJSON. As with some properties attempted to be used in Guild.js (issue #76), erisRole.asJSON does not exist. It used to exist, before Eris devs replaced it with erisRole.json(). See [here](https://github.com/abalabahaha/eris/pull/111).
Even still, erisRole.json would not be necessary …
=> Fixed Role.permissions (extensions) as was empty

Commands/PM/giveaway.js, Modules/Giveaways.js
1) The giveaway command was ignoring any duration other than the default (per issue #70).
2) Giveaways were not ending by themselves at the conclusion of the period set. They could only be ended manually by the creator via PM.
This was because Giveaways.end(), when triggered on a setTimeout() by Giveaways.start() was passing the channelDocument as it was when the giveaway began (thus meaning the participant_ids array was always empty). On the other hand, when ended manually, the channelDocument that was passed to Giveaways.end() was up to date.
Giveaways.end() has been updated to use the live channelDocument, and consequently the problem has been eliminated.
3) The success message PM'd to the creator would always say a winner could not be chosen, even where a winner had been chosen. Also, …
=> Fixed numerous issues with giveaway

Modules/ExtensionStructures/Guild.js
**Added options parameter to Guild.createRole() (extensions)**:
The options parameter remains optional, but if we don't pass it to the function, we then have to use the callback and run Role.edit() on it to specify options for the role we've created. It is much more efficient to be able to specify options when creating a role in the first place. It looks as though this was left out of the original code by mistake.
**Removed non-existent Guild.getChannels**:
Using Guild.getChannels results in:
```
TypeError: erisGuild.getChannels is not a function at Guild.getChannels.cb [as getChannels] (Modules/ExtensionStructures/Guild.js:143:14)
```
Reason: erisGuild.getChannels is indeed _not_ a function. It [doesn't exist](https://abal.moe/Eris/docs/Guild). Also, Guild.channels() is already made …
=> Improvements to Guild (extensions)

Modules/ExtensionStructures/GuildChannel.js, Modules/ExtensionStructures/Message.js
Extensions did not have support for adding, removing or getting reactions. Now they do. I've also updated the pending wiki page to show the new functions and variables.
=> Added reaction support to extensions (message and channel)

Commands/Public/modlog.js
_credit to my friend, SamSoft_
Setting up modlog is easy. `{prefix}modlog enable #channel`. You can check it using `{prefix}modlog`.
Theres an issue, it wasn't checking for isEnabled. it was checking for an inexistent `log_channel` variable.
Replacing that with isEnabled fixes the issue (also, it goes red if its off, and green if its on.)
Spacing is just Atom 😛
=> Modlog command always returning disabled even when enabled

Modules/ExtensionStructures/Message.js
Since Eris' msg.guild was finally removed, those with v6 of Eris will encounter issues with the old AB4 code. While this was updated for GAB in issue #91, the change was missing from the extension Message property.
Fixed.
=> Fixed message.guild not working in extensions

Modules/ExtensionStructures/Sandbox.js
This simple addition allows a command extension to know its own command key and the command prefix of the guild, so that the extension can provide better error messages or guidance to users.
e.g.
```
channel.createMessage("You did not mention a user. Run `" + commandPrefix + commandKey + " <message> @user`");
```
=> Added commandKey and commandPrefix to cmd extensions

Commands/Public/translate.js, Configuration/auth.json, Configuration/commands.json, Events/messageCreate.js, Modules/MicrosoftTranslate.js, package.json
Following the retirement of Microsoft DataMarket at the end of March 2017, the translation command and auto-translate feature will no longer work. Additionally, those new to AB/GAB have not been able to register API keys on DataMarket as this was closed in December 2016.
Given that Microsoft provides an excellent translation API for free (with up to 2 million characters per month), it seems sensible to continue using Microsoft (as opposed to other translation APIs).
The translation command and auto-translate feature are both now fully working in GAB, using the new MS Cognitive Services API.
Existing GAB hosters will need to:
1. obtain a Cognitive Services API key (I will post instructions on how to do so below).
2. edit their Configuration/auth.json to specify the new API key (with the …
=> Translation now uses MS Azure Cognitive Services

Commands/Public/help.js
Because the GAB bot has been down for quite some time and is often slow, I propose we change it to the Github's wiki that we have setup instead.
Sorry if I screwed something up while doing this PR, I barely have used GitHub.
The link changes have been confirmed to work on HuskyBot.
=> Change wiki link in "Help" To github instead of GAB bot.

Modules/ExtensionStructures/InternalBot.js
Profile field key deletion wasn't working because the member document wasn't markModified before save. Easy fix.
=> Fixed profile_fields key deletion in bot.deleteMemberDataKey()

Web/views/pages/maintainer-bot-user.ejs
Actually Discord allows bots setting their status to DnD, so why not?
=> Ability to DnD in the maintainer console
