GilbertGobbels/GAwesomeBot

Commands/PM/profile.js

Signed-off-by: KingDGrizzle <kingdgrizzle@gmail.com>

Fixed Profile Tag bug, this fixes #24, but its not embedded.

---

Commands/Public/meme.js

Copied over from AB3. Otherwise, the meme command in GAB is case-sensitive.

Fixed case sensitivity in meme command

---

Commands/Public/time.js

Time zone in the time command was broken as the timestamp used was static.

Fixed timezone in time command

---

Commands/PM/profile.js

Location showed as undefined as it not set under `userDocument.profile_fields`.

Fixed bug in profile PM where location would show as undefined

---

Commands/Public/disable.js

Removed ability to disable the disable & enable commands from the chat.

---

Web/WebServer.js

Fixed avatar getting reset in maintainer console

---

Commands/Public/dog.js

Fix for #46 and re-make of #47 cause I made a booboo

Fix for dog command

---

Modules/ExtensionStructures/Extension.js

Fixed writeStore and deleteStore in extensions. Neither were working
because store isn't present in the DB extensions schema. There may be a
more efficient fix in the long-run but this does the job nevertheless.
Responding to issue #4.

Fix for extension.writeStore and deleteStore

---

Commands/Public/countdown.js

Signed-off-by: KingDGrizzle <kingdgrizzle@gmail.com>

Fix of countdown for File Systems which don't ignore capitalization.

---

Web/views/partials/header.ejs

Fixes #60 
Signed-off-by: KingDGrizzle <kingdgrizzle@gmail.com>

Fix for Status Button being broken while logged in with some name lengths

---

Commands/Public/streamers.js

Wrong function was called on streamers array traversal

Fix for streamers command

---

Modules/ExtensionStructures/PermissionOverwrite.js

Fixed permissionsOverwrite.has

---

Commands/Public/anime.js

This provisional fix switches the anime command to use the current Kitsu API, which powers the kitsu.io website. While this API is going to be replaced, there are no signs of any significant development in that respect. So in the meantime, this gets the anime command working.
See issue #20.

Provisional fix for anime command

---

Events/voiceChannelJoin.js
Events/voiceChannelLeave.js

Restrict chars in VoiceText text channel name

---

Web/WebServer.js
Web/views/pages/admin-strikes.ejs

Perhaps not perfect but it does the trick, while also avoiding page reloads. A bit of a pain, as the strikes aren't indexed in the db. Accomplished nevertheless.

Added individual strike removal to Admin Console

---

Database/Driver.js
Events/ready.js
Modules/StreamChecker.js
Modules/StreamerUtils.js
Modules/StreamingRSS.js

Fixes for streaming events (RSS and Streamers). Events triggered about every 10 minutes.
Note: bluebird assigned to mongoose.Promise as a Promise library because mpromise is deprecated.

Fix streaming events(RSS, Streamers)

---

Database/Schemas/serverConfigSchema.js
Events/messageCreate.js
Web/WebServer.js
Web/views/pages/admin-filters.ejs

As described in the two commits contained, I have fixed numerous issues with filter handling, and the filters should now work as intended.

Numerous fixes to filter handling

---

Events/messageUpdate.js
Platform/Discord.js
bot.js

*Boy, did this take long*
They are finally here. And they work.
I've fixed all the bugs that made messageEdited not to log the message.
Its been mostly a rewrite

[Bug-Fix] Message Edit Logs actually log things

---

Web/views/pages/admin-voicetext-channels.ejs

Fixed typo in Voicetext menu

---

Events/messageUpdate.js
Modules/ExtensionRunner.js
Modules/RSS.js
bot.js

~Change to package.json will soon reflect this, so we don't install unnecessary things!~

Completely removed domains

---

Commands/Public/cat.js
Commands/Public/dog.js
Commands/Public/pokedex.js

This PR changes some small things in a few commands
- cat
- dog
- pokedex

Redesign of some commands

---

Commands/Public/anime.js

data.attributes.averageRating is now being served as string instead of number, so just convert it to a number before trying to use .toFixed on it.
This fixes #132

Fixed anime command

---

Web/views/partials/extension-gallery.ejs

Fix for Extension Queue

---

Modules/ExtensionStructures/InternalBot.js

Actually a great piece of XSS right?
Actual PoC code will be shared only with devs, after merge it will get revealed to public.

Fix an issue in extensions that allows users to mess the bot up

---

Modules/ExtensionStructures/InternalBot.js

This actually uses the same PoC as #158.
This is untested.

Again fix a XSS issue for bot.awaitMessage and bot.getMember

---

Commands/Public/help.js

Shows guild extension commands in the help guidance on the public help command (only those available to the user, based on their bot admin level) with usage as defined in the extensions editor. 
Also displays the extension's usage and extended help guidance for individual extension commands, just like any other command. Does not display the link to the wiki for extension commands (as, obviously, the wiki will not list extension commands 😉).

Support guild extensions in help
